name: Deploy to AWS
on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Latest Repo
        uses: action/checkout@master
        
      - name: Generate Deployment Package
#       This is simply packing all our build file into a zip folder. this zip folder is kept in S3 and is later unzipped and run in order to generate the docker image
      - run: zip -r deploy.zip * -x "**node_modules**"
      
#       This will generate a unique time stamp that is used to ship our zip file to S3
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
        
      - name: Run string replace
        uses: frabet/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
          
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: beanstalk-deployment
          environment_name: Beanstalkdeployment-env
          version_label: "beanstalk-deployment-${{ steps.format-time.outputs.replaced }}"
          region: eu-west-2
          deployment_package: deploy.zip
